# Generated by Django 4.2.1 on 2023-05-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='number',
        ),
    ]
